Implement first version of beamchmark
membraneframework/beamchmark pull request #1
Opened 2021-11-22 13:49 UTC by mickel8

related to membraneframework/membrane_rtc_engine#35

2021-11-24 14:22 UTC, Qizot requested changes
I think that we are lacking the description of what the benchmark measures and how, why we need that package and how is it better than other solutions. I don't think that the example in readme is just enough as it requires all the people to decode it to be honest.  Not everyone has to know that there are different kinds of schedulers etc.

2021-11-24 14:22 UTC, Qizot commented on .editorconfig
> +root = true
isn't it your personal file?

2021-11-24 14:22 UTC, Qizot commented on README.md
> +Tool for measuring EVM performance.
I would add some text description what gets measured and how in the readme, it is not that easy to read the numbers below.

2021-11-24 14:22 UTC, Qizot commented on lib/beamchmark.ex
> +    output_dir = opts[:output_dir] || @default_output_dir
nitpick: `Keyword.get(opts, :output_dir, @default_output_dir)` looks nicer (at least for me).

2021-11-24 14:22 UTC, Qizot commented on lib/beamchmark.ex
> +    :noop
why do you return `:noop`? I would guess that it means `no operation` and in this case you did some work

2021-11-24 14:22 UTC, Qizot commented on lib/beamchmark.ex
> +        File.read!(Path.join(base_dir, @results_file_name))
this could be futher divided to use pipe

2021-11-24 14:22 UTC, Qizot commented on lib/beamchmark/scheduler_info.ex
> +  alias __MODULE__
That alias does noting

2021-11-24 14:24 UTC, mickel8 commented on lib/beamchmark/scheduler_info.ex
> +  alias __MODULE__
Actually it's needed for typespecs and documentation to make dialyzer happy

2021-11-24 14:26 UTC, mickel8 commented on .editorconfig
> +root = true
It's taken from `membrane_template_plugin`

2021-11-26 10:48 UTC, Qizot commented on .editorconfig
> +root = true
Good to know that we have to install a plugin to make use of it :D

2021-11-29 12:11 UTC, mickel8 commented on lib/beamchmark.ex
> +    output_dir = opts[:output_dir] || @default_output_dir
I don't agree :stuck_out_tongue:  I really like this syntax :heart_eyes:

2021-11-29 17:03 UTC, Qizot commented on lib/beamchmark.ex
> +  Scheduler utilization is measured using Erlang's [`:scheduler`](`:scheduler`) module which uses `:erlang.statistics/1`
Does the `[':scheduler...` thing links to erlang documentation? If so then it's really cool and strange at the same time...

2021-11-29 17:03 UTC, Qizot commented on lib/beamchmark.ex
> +  Top level module providing `Beamchmark.run` API.
Really nice docs :)

2021-11-29 17:03 UTC, Qizot commented on lib/beamchmark.ex
> +    output_dir = opts[:output_dir] || @default_output_dir
So be it  😛

2021-11-29 17:03 UTC, Qizot commented on lib/beamchmark.ex
> +    Mix.shell().info("Running scenario")
nitpick: I would add some new lines here so it does not look like a big blob, I don't mean after each line but where it makes sense.

2021-11-29 17:03 UTC, Qizot commented on lib/beamchmark.ex
> +    Process.sleep(opts[:delay] || 0)
Can we put all the `opts` accesses at the top of the functions including their defaults?

2021-11-29 17:03 UTC, Qizot commented on lib/beamchmark.ex
> +  defp bench(opts) do
I guess this can take `duration` directly if we apply the comment above.

2021-11-29 17:03 UTC, Qizot commented on lib/beamchmark.ex
> +    File.write!(out, results)
`File.write!` on its own returns the `:ok` atom (regarding on returning the atom below).

2021-11-29 17:03 UTC, Qizot commented on lib/beamchmark/scheduler_info.ex
> +  alias __MODULE__
Strange...

2021-11-29 17:03 UTC, Qizot commented on lib/beamchmark/utils.ex
> +  # TODO what is the return type?
I believe it is a `binary/String` [here](https://github.com/elixir-lang/elixir/blob/a64d42f5d3cb6c32752af9d3312897e8cd5bb7ec/lib/elixir/lib/io/ansi.ex#L4)

2021-12-01 16:54 UTC, mickel8 commented on lib/beamchmark.ex
> +  Scheduler utilization is measured using Erlang's [`:scheduler`](`:scheduler`) module which uses `:erlang.statistics/1`
Yeah, it links to Erlang docs. I took this from Elixir source code :roll_eyes:

2021-12-02 08:28 UTC, Qizot approved these changes
LGTM!

2021-12-02 08:28 UTC, Qizot commented on README.md
> +For more information please refer to API docs.
I would probably add here or maybe in an API some information compring it to `benchee` and when you should use one and when another, but I will leave it up to you.

2021-12-02 11:15 UTC, merged