Support for windows
membraneframework/beamchmark pull request #21
Opened 2022-05-11 07:30 UTC by shuntrho

Fixed Beamchmark crashing on Windows.
Fixed Beamchmark not opening HTML report due to wrong path format.
Added average CPU utilization measurement for Windows.

2022-05-11 14:14 UTC, DominikWolek requested changes

2022-05-11 14:14 UTC, DominikWolek commented on lib/beamchmark/suite/cpu/cpu_task.ex
> +    {cpu_util_result, 0} = System.cmd("wmic", ["cpu", "get", "loadpercentage"])
This is weird - why not just call `cpu_snapshot(Utils.os())` in `run_poll` and get rid of this zero-arity `cpu_snapshot`?

2022-05-11 14:14 UTC, DominikWolek commented on lib/beamchmark/utils.ex
> +    {_family, name} = :os.type()
I'd say this name is not descriptory enough. Maybe `os_name`? What do you think?

2022-05-11 14:14 UTC, DominikWolek commented on lib/beamchmark/suite/system_info.ex
> +      os: Utils.os(),
Again, maybe `os_name`, or something similar?

2022-05-11 14:14 UTC, DominikWolek commented on lib/beamchmark/suite/cpu/cpu_task.ex
>    """
I think there should be an information in README about which systems are supported.

2022-05-11 14:14 UTC, DominikWolek commented on lib/beamchmark/formatters/html.ex
> +    end
There's no case clause for FreeBSD - this case will throw an error. 

AFAIK `xdg-open` is available on the FreeBSD, and probably whole beamchmark will work on it. But, if you don't want to support it, maybe you should throw the custom error with explanation, that this system is not supported.

Also, I think it's a good idea to describe which systems are supported in the README file.

2022-05-11 14:14 UTC, DominikWolek commented on lib/beamchmark/suite/cpu/cpu_task.ex
> +      |> Kernel./(1)
Why not just use `Float.parse/1`?

2022-05-13 07:20 UTC, shuntrho commented on lib/beamchmark/suite/cpu/cpu_task.ex
> +    {cpu_util_result, 0} = System.cmd("wmic", ["cpu", "get", "loadpercentage"])
Hmm, in the current approach I like the fact that we don't have to bother with the operating system in the `run_poll`, just calling `cpu_snapshot/0` which checks os for us.

2022-05-13 07:29 UTC, shuntrho commented on lib/beamchmark/utils.ex
> +    {_family, name} = :os.type()
I will go with `get_os_name`

2022-05-16 12:25 UTC, roznawsk reviewed
Due to windows taking around a second to get cpu utilization (averaged from that second), I implemented `run_poll` separately for Windows by making async queries for cpu utilization.

2022-05-18 13:00 UTC, DominikWolek commented on README.md
> +  You can implement your custom formatters by overriding `Beamchmark.Formatter` behavior.
As far as I remember we stick to the British English spelling in the documentation, let's keep the "behaviour".

2022-05-18 13:00 UTC, DominikWolek commented on lib/beamchmark/suite/cpu/cpu_task.ex
> +              [snapshot | cpu_snapshots]
I think this is a debug message left out

2022-05-18 13:00 UTC, DominikWolek commented on lib/beamchmark/suite/cpu/cpu_task.ex
> +  def(cpu_snapshot(:Windows, pid)) do
```suggestion
  defp cpu_snapshot(:Windows, pid) do
```

2022-05-18 13:00 UTC, DominikWolek commented on lib/beamchmark/suite/cpu/cpu_task.ex
> +  def(cpu_snapshot(:Windows, pid)) do
This is still little weird for me. Maybe just change is to something like `windows_cpu_snapshot(pid)`? First argument is ignored anyway.

2022-05-20 11:43 UTC, DominikWolek approved these changes
![image](https://user-images.githubusercontent.com/34174337/169521331-fe010c44-2785-412a-8f84-8dde80a1df81.png)

2022-05-20 12:50 UTC, merged